### PR TITLE
Use 'Misc Tamsyn' as default font in copland theme

### PR DESCRIPTION
**Pull request by xelkarin**

### CODE REVIEW

**Comment by xelkarin** [comment]
The `Tamzen` font is indexed as `Misc Tamzen` in the font cache. Since the `Tamsyn` and `Tamzen` fonts don't seem all that visually different and the other themes use `Misc Tamsyn`, I've set the default font for the copland theme to `Misc Tamsyn` to match the other themes.

**Comment by lcpz** [comment]
Tamzen is what I currently use for `copland`, so I won't switch to Tamsyn. You can do it in fork.

Also, we should set `Misc Terminus` for those themes that uses it. But I don't know if `Misc {Terminus,Tamsyn,Tamzen}` is standard for every distro. Can you check it?

**Comment by xelkarin** [comment]
It seems that font names are [determined](https://forum.manjaro.org/t/terminus-font-name-fix-after-freetype2-update-to-2-7-1-1/15530) by the `freetype` library. Some distributions may provide fontconfig aliases for these fonts.

**Comment by lcpz** [comment]
I will keep Tamzen and fix its name in Copland.

**Comment by lcpz** [comment]
I changed my mind and decided to meet your user's desire and remove Tamzen.

**Comment by lcpz** [comment]
I changed my mind and decided to meet your user's desire and remove Tamzen.

**Pull request closed without merging**
