### PR TITLE
Change dmenu to rofi with dmenu theme

### PR DESCRIPTION
**Pull request by cheese-cracker**
rofi would provide more customization than dmenu so I thought switching it would be better!

### CODE REVIEW

**Comment by lcpz** [comment]
Add `rofi` as another (commented out) option, instead of forcing its use, and I will merge.

Also add a link to its website, users may not know it.

**Comment by cheese-cracker** [comment]
Where should I add add the link and should I edit readme as well?

**Comment by lcpz** [comment]
> Where should I add add the link

Before the `rofi` code, as a comment.

> should I edit readme as well

No, but you should squash the commits into one.

**Comment by cheese-cracker** [comment]
I have made the changes.

**Pull request merged**
