### PR TITLE
[WIP] unify widget naming

### PR DESCRIPTION
**Pull request by martingabelmann**
related to #162

### CODE REVIEW

**Comment by martingabelmann** [comment]
I started with copland since it does a lot with progress bars which leads to a more complex `theme.widgets.[...].[...]` structure.   
Strace between this branch (left) and the master (right) (droping caches inbetween):
```
% time     seconds  usecs/call     calls    errors syscall	% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------	------ ----------- ----------- --------- --------- ----------
  0.00    0.000000           0       103        10 _llseek	  0.00    0.000000           0       103        10 _llseek
  0.00    0.000000           0       202        11 access     |	  0.18    0.000049           0       202        11 access
  0.00    0.000000           0        44           brk	      |	  0.00    0.000000           0        43           brk
  0.00    0.000000           0         1           clock_getr	  0.00    0.000000           0         1           clock_getr
  0.00    0.000000           0        30           clock_gett	  0.00    0.000000           0        30           clock_gett
  0.00    0.000000           0        14           clone	  0.00    0.000000           0        14           clone
  0.08    0.000023           0       548           close      |	  0.00    0.000000           0       548           close
  0.00    0.000000           0         4           connect	  0.00    0.000000           0         4           connect
  0.00    0.000000           0         6           eventfd2	  0.00    0.000000           0         6           eventfd2
  0.00    0.000000           0         1           execve	  0.00    0.000000           0         1           execve
  0.00    0.000000           0         7           fadvise64_	  0.00    0.000000           0         7           fadvise64_
  0.00    0.000000           0        15           fcntl64	  0.00    0.000000           0        15           fcntl64
  0.00    0.000000           0       322           fstat64	  0.00    0.000000           0       322           fstat64
  0.00    0.000000           0        26           fstatfs64	  0.00    0.000000           0        26           fstatfs64
  0.11    0.000030           0       259         3 futex      |	  0.17    0.000048           0       264         4 futex
  0.00    0.000000           0        14           getdents64	  0.00    0.000000           0        14           getdents64
  0.00    0.000000           0         3           getegid32	  0.00    0.000000           0         3           getegid32
  0.00    0.000000           0         5           geteuid32	  0.00    0.000000           0         5           geteuid32
  0.07    0.000019          19         1           getgid32   |	  0.00    0.000000           0         1           getgid32
  0.00    0.000000           0         1           getpeernam	  0.00    0.000000           0         1           getpeernam
  0.00    0.000000           0         2           getresgid3	  0.00    0.000000           0         2           getresgid3
  0.00    0.000000           0         2           getresuid3	  0.00    0.000000           0         2           getresuid3
  0.00    0.000000           0         2           getsocknam	  0.00    0.000000           0         2           getsocknam
  0.00    0.000000           0       628           gettimeofd	  0.00    0.000000           0       628           gettimeofd
  0.00    0.000000           0         1           getuid32	  0.00    0.000000           0         1           getuid32
  0.00    0.000000           0         1           lseek	  0.00    0.000000           0         1           lseek
  0.07    0.000019           0       760       600 lstat64    |	  0.00    0.000000           0       760       600 lstat64
  0.10    0.000027           0       223           mmap2      |	  0.00    0.000000           0       223           mmap2
  0.00    0.000000           0       114           mprotect	  0.00    0.000000           0       114           mprotect
  0.00    0.000000           0         9           munmap	  0.00    0.000000           0         9           munmap
  8.58    0.002335           1      2975      2459 open	      |	 27.49    0.007672           3      2975      2459 open
  0.00    0.000000           0        19           pipe2	  0.00    0.000000           0        19           pipe2
  0.00    0.000000           0       306           poll	      |	  0.00    0.000000           0       290           poll
 15.89    0.004323           3      1382         1 read	      |	 14.89    0.004154           3      1379         1 read
  0.00    0.000000           0         1           readlink	  0.00    0.000000           0         1           readlink
  0.08    0.000022           0        49        21 recv	      |	  0.00    0.000000           0         7           recv
  0.00    0.000000           0       139         4 recvmsg    |	  0.00    0.000000           0       146         4 recvmsg
  0.00    0.000000           0        29           rt_sigacti	  0.00    0.000000           0        29           rt_sigacti
  0.00    0.000000           0        11           rt_sigproc	  0.00    0.000000           0        11           rt_sigproc
  0.00    0.000000           0        12           send		  0.00    0.000000           0        12           send
  0.00    0.000000           0         5           sendmsg	  0.00    0.000000           0         5           sendmsg
  0.00    0.000000           0         1           set_robust	  0.00    0.000000           0         1           set_robust
  0.00    0.000000           0         1           set_thread	  0.00    0.000000           0         1           set_thread
  0.00    0.000000           0         1           set_tid_ad	  0.00    0.000000           0         1           set_tid_ad
  0.00    0.000000           0         1           shmat	  0.00    0.000000           0         1           shmat
  0.00    0.000000           0         1           shmctl	  0.00    0.000000           0         1           shmctl
  0.00    0.000000           0         1           shmdt	  0.00    0.000000           0         1           shmdt
  0.00    0.000000           0         1           shmget	  0.00    0.000000           0         1           shmget
  0.00    0.000000           0         1           shutdown	  0.00    0.000000           0         1           shutdown
  0.00    0.000000           0         4           sigreturn  |	  0.00    0.000000           0         3           sigreturn
  0.00    0.000000           0         4           socket	  0.00    0.000000           0         4           socket
 12.26    0.003334          30       110        55 stat64     |	  0.00    0.000000           0       110        55 stat64
  0.00    0.000000           0         1         1 statfs	  0.00    0.000000           0         1         1 statfs
  0.00    0.000000           0         1           ugetrlimit	  0.00    0.000000           0         1           ugetrlimit
  0.00    0.000000           0         3           uname	  0.00    0.000000           0         3           uname
 61.57    0.016748        1523        11           waitpid    |	 56.91    0.015880        1444        11           waitpid
  1.18    0.000321          14        23           write      |	  0.36    0.000101           5        22           write
  0.00    0.000000           0       123           writev	  0.00    0.000000           0       123           writev
------ ----------- ----------- --------- --------- ----------	------ ----------- ----------- --------- --------- ----------
100.00    0.027201                  8564      3165 total      |	100.00    0.027904                  8512      3145 total
```

**Comment by copycat-killer** [comment]
How do you verify the reliability of your testing?

Read [here](https://github.com/copycat-killer/awesome-copycats/issues/162#issuecomment-284220208) if you didn't.

**Comment by copycat-killer** [comment]
Also, this implies to *uniform* every current theme, and to set a template for future ones.

Probably this is more a work for a dedicated submodule: an extension of `beautiful` (or something which wraps it) that inspects `theme.lua` and do the uniformation itself.

Maybe instead of redefining variables, you can create a table of pointer at the end of the `theme.lua` file, which is then processed by this ipotetical submodule. Just my first thoughts, anyway.

**Comment by martingabelmann** [comment]
> How do you verify the reliability of your testing?

I didnt since I thought the comparison of the two versions (with awesome.quit() at the end of rc.lua to stop at the same point) is enough.

> Also, this implies to uniform every current theme, and to set a template for future ones.

That was actually meant with "uniform" (and which is why this is WIP, since the other themes should follow if this one gets approved). A template is not necessary (but probably helpful) since one is still free to do what one wants, just the way of handling internal/external widget objects, helper variables etc.. changes (and how specific widgets are named). I also thought about just putting all `widget` and `icon` objects into the `theme.widgets.{}` table but wasnt sure if this breaks some special use cases.

> Probably this is more a work for a dedicated submodule

A wrapper that makes "widget registration" uniform might be elegant. However, my lua skills arent that good as I cant give any comment about which kind of problems might appear then or how to do this ordinary...
In any case there are these "standard widgets" that have to be named/stored equally over the themes such that the rc.lua can handle it, so we cannot prevent from introducing conventions. Actually there are conventions already but not stricly uniformed as in this approach.

**Comment by copycat-killer** [comment]
> I didnt since I thought the comparison of the two versions (with awesome.quit() at the end of rc.lua to stop at the same point) is enough.

I'm afraid it may not. You should also have to start from the same memory stack. Use tracing along with `Xephyr` too.

> A wrapper that makes "widget registration" uniform might be elegant.

I believe this should be the go. I'll investigate a bit.

**Comment by lunacorn** [comment]
I've heavilly modified this and want to know how to properly give credit

**Comment by martingabelmann** [comment]
To be honest, my opinion on this has changed a bit during the last year(s). I think that @lcpz`s  note in https://github.com/lcpz/awesome-copycats/issues/162#issuecomment-283942066 was quite right. Indeed I didnt had a look at this again for more than a year now. So it might not be worth the effort (at least for myself)...

Of course, if you want to take over and already modified the approach, I shall close this PR and you may open a new one?

**Comment by martingabelmann** [comment]
okay ill close this for now and lets see whether #162 wil be taken over by @lunacorn .
merry :x:-mas

**Pull request closed without merging**
